---
environments:
  dev:
    docker:
      APP: django
      VERSION: "0.0"
      registry: ecr
      url: .dkr.ecr.us-east-1.amazonaws.com
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      filename: Dockerfile
      filepath: docker
      arguments:
        APP: "{{ APP }}"
        VERSION: "{{ VERSION }}"

    microservice:
      cluster:
      cpu: 128
      memory: 64
      replicas: 4
      domain_name: django.dev.x.com
...
